### ISSUE TITLE
More headache cleanup

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#1179]
## forum index

* [x] Add ForumFilter region
* [x] Add DestinationBar's (see #1178)

## forum show

* [x] remove border and padding from `ForumPost` when `$mobile`

## travelmate index

* [x] create TravelmateAbout region with block

```
    subtitle = trans('content.travelmate.description.title')
    content = collect()->push(component('Body')->with('content', travelmate.description.text))
```

* [x] create About region with block

```
    subtitle = trans('content.action.more.about.text')
    content = collect()
        ->push(component('Link')->... 

        // trans('menu.footer3.about')
        // route(config('menu.footer3.about')) <- will it work?
        
        // trans('menu.footer-social.facebook')
        // route(config('menu.footer-social.facebook')) <- make it external

        // + twitter
```

## travelmate show

* [x] Add DestinationBar's (see #1178)

## flight index

* Rename FlightTitle to Title and re-use it in travelmate show
* Make Title smaller when on $mobile

## flight show

* [x] Add DestinationBar's (see #1178)
