### ISSUE TITLE
[meta] Improve forum comment usability

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#944]
* [x] Relative helper link https://github.com/tripikad/trip2/issues/942
* [x] Voting to the top https://github.com/tripikad/trip2/issues/943
* [ ] Kill comment pager https://github.com/tripikad/trip2/issues/904
